title: Paper Notes
short_title: Papers
subtitle: Summaries and takeaways from research papers I read.
description: Paper notes by Nechintosh.
author:
  name: nech
  email: 
language: en-US
timezone: America/New_York
url: "https://nech07.github.io"
baseurl: "/flying-cat"
permalink: "/:year/:month/:day/:title/"
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-seo-tag
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: paper
      show_meta: true
      toc: true
      nav_back: true
  - scope:
      path: "assets/css"
    values:
      sitemap: false
exclude:
  - README.md
  - scripts
  - node_modules
  - vendor
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about/
